language: ruby
rvm: 2.3.1
script: bundle exec jekyll build && bundle exec rake minify && bundle exec rake s3
branches:
  only:
  - releases
env:
  global:
  - AWS_REGION="ap-northeast-1"
  - AWS_BUCKET_NAME="shop.sasaki.farm"
  - JEKYLL_ENV=production
  - secure: KCYq/4L5SPGfALBGbR7WNgNCyZfjxuS7Y445hnOlV9tBamyGgaHSfndHpWW7JZC9l5AieLV28HqiXWEtXBynw+N/TI91F1Zq/yanLVPYK93eXwq46Y8Du7SMInG20XUeqDsV2pSHAyjz3gkVjMTKS4tnYbPaOM/lWJxYPbAH2wVoacD1Qb/zDqj8WcuZEKFLikbyPxIcrUl3NF5In3cxbpvCnS8pu8t+Yh/qQrVwVWDgROy7Y2lQa5kFk5bJRF8QM1vVXvJeQ5dqK15hgQHlmbvhh7AShwuWazTt6sHV7d8mLmjrfEHcnkwDuYHjo1AyYztRo9t03OkXABmbir4fBRtp9bExQMiYNUuE8eGYjIV6nHTDPg3v0Ay8Qwb5ZySqkTG3fHXdAHUSRlXS5zSlYLRJfVf20vsGKtP1wNmSVr+e1a3vmldCLAqXG+BCSMI0CaxTkoteEE1s/7g7WjKJsREFOVaHNxhkywgNFTVFwrL4c9ebq+141+FQE7oM+NrR2NyeHn9bMgVnXFEScinpvnzcWFq35HQGhhhujeffyu8B2wkbHYc6SOYg/TdrjdSSTWpVd3pDJ0gYMmUy8qK90ySnQ+0GbhQzd/eQqBFUk4Beo88yQjBfuclu2s3jN+urNd8GM+fi3t/7lr5pEco5L2PyPVRQAJsGSdt6/5dVl5M=
  - secure: HOg+fIQJmDgi5hIiGxTHgLL96qP898OcG4brBPyfnRB4PaQGzW0FsHPgG/gsdimvyxiGHKKeJfkQjYohZj7knYRcouK0eURprSKLrb13ddC2+EeC9+VBq9cA2MgeJUTRzbvSx+1vjEcyEYtjE88G7Zi7Hx8hZRZZMyNzPjMlMWMIa3pNox5YTjFx9ucSHjTt82MaoR6hwrskOsmaK/UOMg5uQNYkfUTG9zu7U142w2pkN6IKTs0+o7aUZbXOAwka1I5wz4HItVc/MJng0ENx16w5/pYHg7sgykSBAPie6N/ZCmggq33q7whjJ6D4sn2/vyh1qkklWWa7nikG2rC0n9sUpkTSXfhMb0t74SNWpkAebJhvO7V2JO0VIVYJM2UoaElRiGgwmHNHUQdSdKEWxE66K0O0EJKKUY206SvobC3HwmHxwHWgzpQoJ3NLTQLkHhlof8dKRKdPpYUwJ9FNbPSH4//4jgOiGIR99jp2XDPxbbdL0o20Vb5xL2J5q9PQRy9pAhU3cWW1bj09HBlXTyCkfg7MnhYaEOayMpBXbyKpCra7zgLf+gkkxgmL3LV9AO0oT0B48qOIwzv16f35lyWrDGpdy1+nMow1+nFcW3G2Str30IBi1lLcVuvl2+WGvnbIdOrr2rpdaPg3w042d+NitpOpjFDn14E4cgh3dcI=
