# Site settings
title: "佐々木農場"
author: "佐々木文明"
description: "佐々木農場のサイトです"
keywords: "Agriculture, Rice, Organic Farming, Sales, 農業、無農薬、米"
biography: "無農薬の米の販売やってます。"
colophon: "© MMXIII — MMXVI by Arda Karaduman"

baseurl: ""
url: "http://shop.sasaki.farm"

twitter_username: kazuekaraduman
facebook_username: karaduman.kazue
google-analytics: UA-56175514-1

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
